TaskBundle\Entity\Task:
 getters:
  ValidDate:
   - "True": { message: "Дата окончания должна быть больше даты начала" }
TaskBundle\Entity\Subtask:
 getters:
  ValidDate:
   - "True": { message: "Дата окончания не должна быть больше даты окочания основной задачи " }