category:
    path:     /
    defaults: { _controller: "TaskBundle:Category:index" }

category_show:
    path:     /{id}/show
    defaults: { _controller: "TaskBundle:Category:show" }

category_new:
    path:     /new
    defaults: { _controller: "TaskBundle:Category:new" }

category_create:
    path:     /create
    defaults: { _controller: "TaskBundle:Category:create" }
    methods:  POST

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "TaskBundle:Category:edit" }

category_update:
    path:     /{id}/update
    defaults: { _controller: "TaskBundle:Category:update" }
    methods:  [POST, PUT]

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "TaskBundle:Category:delete" }
    methods:  [POST, DELETE]
